# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: projets-sig@makina-corpus.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://geotrek.fr" # the base hostname & protocol for your site
analytics: UA-40919875-1

paginate_path: "/actualites/:num/"
paginate: 6
excerpt_separator: <!--more-->

translate_meta:
  es:
    title: Geotrek, gestiona y promueve tus rutas y actividades turísticas
    description: Solución Webmapping compuesta de una herramienta SIG específica, una web y una aplicación móvil
    keywords: geotrek, GIS, trek software
  en:
    title: Geotrek, manage and enhance your paths and tourist activities
    description: Webmapping application suite composed of a GIS business-specific tool, a website and a mobile application
    keywords: geotrek, GIS, trek software
  fr:
    title: Geotrek, gérez et valorisez vos sentiers et activités touristiques
    description: Suite logicielle webmapping composée d’un outil métier SIG, d’un site internet et d’une application mobile
    keywords: geotrek, SIG, logiciel randonnée, application randonnée

# Build settings
markdown: kramdown
future: true
sass:
    sass_dir: assets/css/
    style: :nested

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

translate_menu:
  es:
    home:
      name: "Inicio"
      url: "index-es.html"
    product:
      name: "Producto"
      url: "product-es.html"
    references:
      name: "Referencias"
      url: "references-es.html"
    contact:
      name: "Contacto"
      url: "contact-es.html"

  en:
    home:
      name: "Home"
      url: "index-en.html"
    product:
      name: "Product"
      url: "product-en.html"
    references:
      name: "References"
      url: "references-en.html"
    contact:
      name: "Contact"
      url: "contact-en.html"

  fr:
    home:
      name: "Accueil"
      url: "index.html"
    product:
      name: "Produit"
      url: "produit.html"
    references:
      name: "Références"
      url: "references.html"
    ressources:
      name: "Ressources"
      url: "ressources.html"
    contact:
      name: "Contact"
      url: "contact.html"

gems:
  - jekyll-paginate
